language: python
python:
    - "3.3"
    - "3.4"
    - "3.5"
    - "3.6"
install:
    - pip install -e .
before_script:
    - pip install -r requirements.txt
script:
    py.test --cov-report= --cov=chess
after_success:
    coveralls
